"use client";

import { useState } from "react";

/**
 * Renders a generated PNG asset, falling back to an emoji glyph if the image
 * is missing (or still being generated by image-gen).
 */
export function AssetImage({
  category,
  name,
  emoji,
  size = 80,
  className = "",
}: {
  category: "food" | "ingredient" | "mascot" | "meal";
  name: string;
  emoji?: string;
  size?: number;
  className?: string;
}) {
  const [failed, setFailed] = useState(false);

  if (failed) {
    return (
      <span
        className={`inline-block leading-none select-none ${className}`}
        style={{ fontSize: size * 0.85 }}
      >
        {emoji ?? "❓"}
      </span>
    );
  }

  return (
    <img
      src={`/images/${category}/${name}.webp`}
      alt={name}
      width={size}
      height={size}
      draggable={false}
      onError={() => setFailed(true)}
      className={`inline-block select-none ${className}`}
      style={{ objectFit: "contain" }}
    />
  );
}
